name: linux

on:
  push:
    branches: [ main ]
    tags: ["*.*.*"]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@63069e3931dedbf3b63792097479563182fe70d1 # v1.2.18
      with:
        key: ${{ github.job }}-${{ runner.os }}-${{ runner.arch }}
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
          gcc \
          gobject-introspection \
          gtk-doc-tools \
          libcairo2-dev \
          libfreetype6-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          libgraphite2-dev \
          libicu-dev \
          pkg-config \
          help2man
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.12'
    - name: Install Python Dependencies
      run: pip3 install -r .ci/requirements.txt --require-hashes
    - name: Setup Meson
      run: |
        ccache --version
        meson setup build \
          -Dauto_features=enabled \
          -Dchafa=disabled \
          -Dgraphite=enabled \
          -Dkbts=enabled \
          -Doptimization=2 \
          -Ddoc_tests=true \
          -Dragel_subproject=true
    - name: Build
      run: meson compile -Cbuild
    - name: Test
      run: meson test --print-errorlogs -Cbuild
    - name: Dist
      run: |
        git reset --hard HEAD # ragel may have modified the source tree
        meson dist --no-tests -Cbuild
    - name: Generate Documentations
      run: ninja -Cbuild harfbuzz-doc
    - name: Deploy Documentations
      if: github.ref_type == 'tag'
      run: .ci/deploy-docs.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        REVISION: ${{ github.sha }}
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: harfbuzz
        path: build/meson-dist/harfbuzz-*.tar.xz
        if-no-files-found: error

  release:
    name: Create and populate release
    needs: build
    runs-on: ubuntu-24.04
    if: contains(github.ref, 'refs/tags/')
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: harfbuzz
      - name: Check for release
        id: create_release
        run: |
          if ! gh release view ${{ github.ref_name }}; then
            python3 src/check-release-notes.py NEWS ${{ github.ref_name }} > RELEASE_NOTES
            gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-file RELEASE_NOTES --draft
          fi
      - name: Populate release
        run: |
          gh release upload ${{ github.ref_name }} harfbuzz-${{ github.ref_name }}.tar.xz --clobber
