name: linux-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install pkg-config gcc ragel gcovr gtk-doc-tools libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev python3 python3-setuptools ninja-build gobject-introspection libgirepository1.0-dev
    - name: install meson and fonttools
      run: sudo pip3 install meson fonttools
    - name: run
      run: meson build -Db_coverage=true -Dglib=enabled -Dcairo=enabled -Dicu=enabled -Dgraphite=enabled -Dfreetype=enabled
    - name: ci
      run: meson test --print-errorlogs -Cbuild

    - name: generate documentations
      run: ninja -Cbuild harfbuzz-doc
    - name: deploy documentations
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: .ci/deploy-docs.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        REVISION: ${{ github.sha }}

    - name: cov
      run: ninja -Cbuild coverage
    - uses: codecov/codecov-action@v1
      with:
        file: build/meson-logs/coverage.xml
