name: linux-ci

on:
  push:
    branches: [ main ]
    tags: ["*.*.*"]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@c92f40bee50034e84c763e33b317c77adaa81c92 # v1.2.13
      with:
        key: ${{ github.job }}-${{ runner.os }}-${{ runner.arch }}
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
          gcc \
          gobject-introspection \
          gtk-doc-tools \
          libcairo2-dev \
          libfreetype6-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          libgraphite2-dev \
          libicu-dev \
          ninja-build \
          pkg-config \
          python3 \
          python3-setuptools
    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.x'
    - name: Install Python Dependencies
      run: sudo pip3 install -r .ci/requirements.txt --require-hashes
    - name: Setup Meson
      run: |
        ccache --version
        meson setup build \
          -Dauto_features=enabled \
          -Dchafa=disabled \
          -Dgraphite=enabled \
          -Doptimization=2 \
          -Db_coverage=true \
          -Ddoc_tests=true \
          -Dragel_subproject=true
    - name: Build
      run: meson compile -Cbuild
    - name: Test
      run: meson test --print-errorlogs -Cbuild
    - name: Generate Documentations
      run: ninja -Cbuild harfbuzz-doc
    - name: Deploy Documentations
      if: github.ref_type == 'tag'
      run: .ci/deploy-docs.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        REVISION: ${{ github.sha }}
    - name: Generate Coverage
      run: ninja -Cbuild coverage-xml
    - name: Upload Coverage
      uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
      with:
        file: build/meson-logs/coverage.xml
