name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
      with:
        key: ${{ github.job }}-${{ runner.os }}-${{ runner.arch }}
    - name: Install Dependencies
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        brew rm -f pkg-config@0.29.2
        brew install \
          cairo \
          freetype \
          glib \
          gobject-introspection \
          graphite2 \
          icu4c \
          meson \
          ninja \
          pkgconf
    - name: Setup Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: '3.12'
    - name: Install Python Dependencies
      run: pip3 install -r .ci/requirements.txt --require-hashes
    - name: Setup Meson
      env:
        PKG_CONFIG_PATH: "/usr/local/opt/libffi/lib/pkgconfig"
      run: |
        brew link --force icu4c
        ccache --version
        meson setup build \
          -Dauto_features=enabled \
          -Ddocs=disabled \
          -Dchafa=disabled \
          -Dcoretext=enabled \
          -Dgraphite=enabled \
          -Doptimization=2 \
    - name: Build
      run: meson compile -Cbuild
    - name: Test
      run: meson test --print-errorlogs -Cbuild
