name: msvc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  msvc:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-latest]
        include:
          - name: msvc-2019-x86
            os: windows-2019
            ARCH: x86
          - name: msvc-2019-amd64
            os: windows-latest
            ARCH: amd64
    name: ${{ matrix.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        variant: sccache
        key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.ARCH }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch : ${{ matrix.ARCH }}
    - name: Install Python Dependencies
      run: |
        pip3 install -r .ci/requirements.txt --require-hashes
    - name: Setup Meson
      run: |
          sccache --version

          # For Windows, meson downloads source tarballs.
          # The endpoint is flaky, so we need to wrap this in a retry loop.
          # (meson handles this internally as of 0.62.0)
          $attempts=1
          $timeout=1
          while ($attempts -le 5 )
          {
            meson setup build `
              --wrap-mode=forcefallback `
              --buildtype=release `
              -Dglib=enabled `
              -Dfreetype=enabled `
              -Dgdi=enabled `
              -Ddirectwrite=enabled

            if ($LASTEXITCODE -eq 0)
            {
              break
            }

            echo "Setup failed, trying again with delay"
            Start-Sleep -Seconds $timeout
            $timeout=$timeout * 2
            $attempts++
          }
    - name: Build
      run: meson compile -Cbuild
    - name: Test
      run: meson test --print-errorlogs --suite=harfbuzz -Cbuild
