name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
      with:
        key: ${{ github.job }}-${{ runner.os }}-${{ runner.arch }}
    - uses: dtolnay/rust-toolchain@nightly
    - name: Install Dependencies
      run: |
        rustup component add \
          rust-src \
          rustfmt \
          clippy \
          --toolchain nightly-x86_64-unknown-linux-gnu
        sudo apt-get update
        sudo apt-get install \
          gcc \
          gobject-introspection \
          gtk-doc-tools \
          libcairo2-dev \
          libfreetype6-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          libgraphite2-dev \
          libicu-dev \
          pkg-config \
          bindgen
    - name: Setup Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: '3.12'
    - name: Install Python Dependencies
      run: pip3 install -r .ci/requirements.txt --require-hashes
    - name: Setup Meson
      run: |
        ccache --version
        meson setup build \
          -Dauto_features=enabled \
          -Dchafa=disabled \
          -Dgraphite=enabled \
          -Doptimization=2 \
          -Dfontations=enabled \
          -Dharfrust=enabled
    - name: Build
      run: meson compile -Cbuild
    - name: Test
      run: RUST_BACKTRACE=1 meson test --print-errorlogs -Cbuild
